import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - eacz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Head>
        <meta name='keywords' content='nextjs react node' />
      </Head>

      <Navbar/>

      <main className={styles.main}>
        <h1>Home Page</h1>
        <h1 className={styles.title}>
          go to <Link href='/about'>About</Link>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>
      </main>
    </div>
  )
}
