import Head from 'next/head'
import Navbar from '../Navbar'
import styles from './MainLayout.module.css'

const MainLayout = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - eacz</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Head>
        <meta name='keywords' content='nextjs react node' />
      </Head>

      <Navbar />

      <main className={styles.main}>{children}</main>
    </div>
  )
}

export default MainLayout
